### ISSUE TITLE
console error while starting webui

### ISSUE THREAD

**Issue by ride5k** [light-and-ray/sd-webui-lama-cleaner-masked-content#1]
i see the following in my console window:

`*** Extension "sd-webui-lama-cleaner-masked-content" requires "sd-webui-controlnet" which is disabled.`

however, controlnet is installed, enabled, and working properly.

**Comment by light-and-ray** [comment]
Have you disabled my extension? In 1.7 webui there is a bug. Console error says control net is disabled, but according to code it is my extension disabled

- https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/14639

Wait 1.8 webui to fix it or uninstall/enable my extension

**Comment by ride5k** [comment]
ok thanks for that tip, i did re-enable it and when attempting to inpaint a photo the following appeared on the console:
`[F D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\engine\dml_util.cc:118] Invalid or unsupported data type.
Press any key to continue . . .`

i should also point out that i'm on AMD using directml https://github.com/lshqqytiger/stable-diffusion-webui-directml

**Comment by CCpt5** [comment]
I have this console error also, but I think the problem is that I've renamed the controlnet extension folder (and other extension folders) to reorganize them. A1111 lists extension tabs alphabetically based on folder name. I don't believe there's ever been a setting to reorder the extension tabs so as workaround some of us have found you can rename an extensions folder (add a 1, 2, 3, in front for example) to get it to line up in the order you want.

So currently my controlnet is in folder:

D:\stable-diffusion-webui\extensions\3sd-webui-controlnet  (Note the 3 in front of the folder name)

Perhaps there can be an option in settings to manually define which folder CN is located in?

**Comment by light-and-ray** [comment]
Yes, controlnet doesn't have metadata.ini where should be canonical name of extension. So It takes it from folder name

**Comment by light-and-ray** [comment]
It's not a problem, the console log is only a warning
